### ISSUE TITLE
Use for archiving?

### ISSUE THREAD

**Issue by bepolymathe** [Kungsgeten/hypothesis#1]
Thank you for that. It's very helpful. Could we consider a system that allows you to periodically "download" annotations and comments to an "org" file... to build up a kind of archive ?
By the way, why is it limited to 50 ?

**Comment by Kungsgeten** [comment]
Hi! Yes downloading new annotations and appending them to (or perhaps adding to the front of) an existing file seems like a useful feature.

50 is just a number I picked. If I remember correctly the web-API standard is 20 (if no argument is given) and the max is 200.

**Comment by bepolymathe** [comment]
Yes. And I can see the use for an integration in org-brain ;-) 

50 annotations is enough if you can periodically store them offline in a file... but after a day of working on different documents you may have exceeded them.

**Comment by Kungsgeten** [comment]
I've added `hypothesis-to-archive` (see the README). I've also set the limit of imports to the max (200). Seems to work well for me :)

**Comment by bepolymathe** [comment]
It works for me too ! Thanks.
