### ISSUE TITLE
Row order inside Site

### ISSUE THREAD

**Issue by pejaab** [Kungsgeten/hypothesis#3]
Hi @Kungsgeten,

thanks for this nice little package! I just discovered it and hypothes.is in general a couple of days ago. What I feel to be a little inconvenient is the fact, that the highlights are sorted from youngest to oldest according to 'update date'. This leads to the highlights being in the opposite way, I would expect them to be. I realize that I do not know what your use case is and therefore your need may be different...
Looking at the API, I realized it is possible to sort them according to location in the actual site as well. I added this functionality to my clone and was wondering if you'd like to support it? If so I'd be happy to provide this.

Cheers
Peter

**Comment by Kungsgeten** [comment]
Hi!

I didn't know you could sort them in the order of the site, only by date. A problem I encountered when implementing the "archive" function was how to get the newest of the fetched entries. Also when searching I think there was a problem choosing ascending/descending if you gave the API a "not older than this" date.

If you could get the archiving function to work while still maintaining the original order of the highlights that would be great!

**Comment by Kungsgeten** [comment]
Maybe I should've looked at your commit first, before commenting :) It seems like your solution finds the location and then only sorts when inserting the content into the org file. Smart! I'd be happy to see a pull request!

**Comment by pejaab** [comment]
You are right in regards to the working of the solution. This looked like the most straightforward solution for now.

I saw your comment in the code regarding the archiving, but the ordering was the issue that first grabbed my attention :) 
You mean, the ordering of `sites` in the response is not reliable?

**Comment by pejaab** [comment]
I just realized,  that I completely misread your first comment (I think?). Never mind then...

**Comment by Kungsgeten** [comment]
Fixed in #4 thanks!
